version: '3.8'

services:
  # 첫 번째 스프링 애플리케이션: 로그인/회원가입 처리
  db_login_logout:
    image: mariadb:latest
    container_name: mariadb-login-logout
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_login_logout
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
    ports:
      - "3308:3306"  # 외부 포트는 3308로 변경, 내부 포트는 3306
    volumes:
      - mariadb_data_login_logout:/var/lib/mysql
    networks:
      - app-network

  login_logout_service:
    image: seungbinjo/login_logout:v1.1
    container_name: login-logout-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_login_logout:3306/db_login_logout
      SPRING_DATASOURCE_USERNAME: user1
      SPRING_DATASOURCE_PASSWORD: pass1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8085:8085"
    depends_on:
      - db_login_logout
    networks:
      - app-network

  # 두 번째 스프링 애플리케이션: 게시판 처리
  db_notice_board:
    image: mariadb:latest
    container_name: mariadb-notice-board
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db_notice_board
      MYSQL_USER: user2
      MYSQL_PASSWORD: pass2
    ports:
      - "3309:3306"  # 외부 포트는 3309로 변경, 내부 포트는 3306
    volumes:
      - mariadb_data_notice_board:/var/lib/mysql
    networks:
      - app-network

  notice_board_service:
    image: seungbinjo/notice_board:v1.1
    container_name: notice-board-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_notice_board:3306/db_notice_board
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: pass2
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8086:8086"
    depends_on:
      - db_notice_board
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data_login_logout:
  mariadb_data_notice_board:
